### ISSUE TITLE
vnet-manager example configuration only succeeds when configuring lxdbr0

### ISSUE THREAD

**Issue by maartenvdezz** [Erik-Lamers1/vnet-manager#16]
I tried to create the example configuration (config/example), but it did not succeed and gave me the following warning:

`[vnet_manager.operations.machine] [ERROR] Unable to start LXC container vnet-base, got error: Common start logic: Missing parent 'lxdbr0' for nic 'eth0'`

Therefore, I reconfigured lxd with the following YAML config:

```
   cat <<EOF | lxd init --preseed
config:
  images.auto_update_interval: "0"
networks:
- config:
    ipv4.address: auto
    ipv6.address: auto
  description: ""
  managed: false
  name: lxdbr0
  type: ""
storage_pools: []
profiles:
- config: {}
  description: ""
  devices:
    eth0:
      name: eth0
      nictype: bridged
      parent: lxdbr0
      type: nic
  name: default
cluster: null
EOF
```

I suggest to change the "Setup" section in README if lxdbr0 is indeed required.
