### ISSUE TITLE
Static IPv6 address removed when SLAAC used

### ISSUE THREAD

**Issue by arno481** [Erik-Lamers1/vnet-manager#18]
Hi

when I create the following config, and enable radvd (IPv6 address auto configuration), router1 and router3 get a SLAAC address, but their static address is deleted.
````
---

#
#  router1 -aa- router2 -bb- router3
#

switches: 2

machines:
  router1:
    type: router
    interfaces:
      eth12:
        ipv4: 192.168.0.1/24   # Artefact
        ipv6: 2001:0db8:ffff:00aa::1/64
        mac: 00:00:00:00:01:11
        bridge: 0
  router2:
    type: router
    interfaces:
      eth12:
        ipv4: 192.168.0.2/24   # Artefact
        ipv6: 2001:0db8:ffff:00aa::2/64
        mac: 00:00:00:00:02:12
        bridge: 0
      eth23:
        ipv4: 10.0.0.2/24       # Artefact
        ipv6: 2001:0db8:ffff:00bb::2/64
        mac: 00:00:00:00:02:23
        bridge: 1
  router3:
    type: router
    interfaces:
      eth23:
        ipv4: 10.0.0.3/24      # Artefact
        ipv6: 2001:0db8:ffff:00bb::3/64
        mac: 00:00:00:00:03:23
        bridge: 1
````

Then enable RADVD config on router2:
1. Create  /etc/radvd.conf
````
interface eth12
{
        AdvSendAdvert on;
        prefix 2001:db8:400:600::/64
        {
        };
};

interface eth23
{
        AdvSendAdvert on;
        prefix 2001:db8:400:629::/64
        {
        };
};
````

2. systemctl enable radvd
3. systemctl start radvd
