### ISSUE TITLE
Non-existent keys in configuration file do not trigger an error

### ISSUE THREAD

**Issue by Southparkfan** [Erik-Lamers1/vnet-manager#64]
Business as usual, I forgot my ☕:
```
[snip]
  router3:
    type: router
    interfaces:
      eth123:
        epv6: 2001:db8:beef:29::3/64
        mac: '42:42:42:42:09:03'
        bridge: 9
[snip]
```

Obviously, 'evp6' should have been 'ipv6'. However, I didn't get a hard failure during `vnet-manager create`. A configuration without _any_ IPv4 or IPv6 address can be very legitimate, but a configuration with non-existent keys should trigger an error.
